Async IO layer + SCRAM auth
TrackingSoft/Kafka pull request #48
Opened 2020-04-28 13:36 UTC by Nikolo

Add async IO layer for use this module from async based app
Support kafka sasl auth (PLAIN/SCRAM) 
Move build to Dist::Zilla (milla)
Remove any test but they runs automatically from Dist::Zilla

2020-04-29 01:55 UTC, asolovey requested changes

2020-04-29 01:55 UTC, asolovey commented on META.json
> +         "web" : "https://github.com/my-mail-ru/Kafka/issues"
I think it is preferable to use main repository issue tracker - could you update your PR accordingly?

2020-04-29 01:55 UTC, asolovey commented on META.json
> +      "Alex Solovey <asolovey@users.noreply.github.com>",
These are duplicates, and also some private addresses seem to be leaked; I understand that they are in git commit history anyway, but let's remove emails and keep unique names only.

2020-04-29 01:55 UTC, asolovey commented on README.md
> +# CONTRIBUTORS
You'd probably want to add yourself to this list.

2020-04-29 01:55 UTC, asolovey commented on lib/Kafka/IO/Async.pm
> +This module implemets the same interface that usual Kafka::IO module
typo: implements

2020-04-29 01:55 UTC, asolovey commented on lib/Kafka/IO/Async.pm
> +perform arguments validation.
If I am not mistaken, they actually do validate arguments, just may be not too extensively ;)

2020-05-13 20:51 UTC, Nikolo commented on lib/Kafka/IO/Async.pm
> +perform arguments validation.
This is copy-paste from lib/Kafka/IO.pm

2020-05-13 21:38 UTC, asolovey approved these changes

2020-05-13 21:39 UTC, merged